apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gmailaddresses.aumer.dev
spec:
  group: aumer.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                address:
                  type: string
                parentLabel:
                  type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
  scope: Namespaced
  names:
    plural: gmailaddresses
    singular: gmailaddress
    kind: GmailAddress
    shortNames:
    - ga